POST http://localhost:8000/api/buildings/add-building
Content-Type: application/json

{
    "name": "Bagley Hall",
    "code": "BAG",
    "rooms": []
}

###
GET http://localhost:8000/api/buildings/get-buildings/a

###

POST http://localhost:8000/api/rooms/report-positive
Content-Type: application/json

{
    "buildingName": "Savery Hall",
    "roomName": "SAV69",
    "sectionToReport": 4
}

###


GET http://localhost:8000/api/rooms/get-room/SAV69
